license = "MIT"
modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/jace-deb/jace-launcher/issues"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "jace.deb"
displayURL = "https://jace-store-deb.vercel.app/project/jace-friends"
logoFile = "assets/jacefriends/icon.png"
description = "Your Jace Launcher friends list and chat inside Minecraft. See who's online, chat, host your world for friends (with e4mc) and join theirs in one click."

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"
