license = "MIT"
modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/jace-deb/jace-social/issues"

[[mixins]]
config = "jacefriends.mixins.json"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "jace.deb"
displayURL = "https://jace-store-deb.vercel.app/project/jace-social-minecraft"
logoFile = "assets/jacefriends/icon.png"
description = "Jace Social in Minecraft: friends, group chats and voice calls, host your world for friends (with e4all) and join theirs in one click."

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "e4all"
type = "${e4all_type}"
versionRange = "[0,)"
ordering = "NONE"
side = "CLIENT"
